pool:
  vmImage: 'ubuntu-latest'

variables:
  #- group: sonarlogin
  - name: acrServiceConnection
    value: 'testacr'
  #- name: sonarServiceConnection
  #  value: 'sonar-connection'
  - name: aksServiceConnection
    value: 'testaks'

stages:
- stage: BuildAndPush
  displayName: 'Build and Push to ACR'
  jobs:
  - job: Build
    displayName: 'Build and Push'
    steps:
    - checkout: self
    - task: Docker@2
      displayName: 'Build and push Docker image'
      inputs:
        command: 'buildAndPush'
        containerRegistry: '$(AcrServiceConnection)'
        repository: 'testing'
        Dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          $(Build.BuildId)
    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact: drop'
      inputs:
        PathtoPublish: deployment/deployment.yaml
